name: Daily Python Job

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run_python_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python ./project.py   

      - name: push to github
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: 'main'
          commit-message: 'publish'
          force-add: 'true'
          files: '.'
          name: giladAlboher
          email: gilad1299@gmail.com
          push-args: '--set-upstream origin main'
